### ISSUE TITLE
Year only showing 1970-72 range

### ISSUE THREAD

**Issue by bshorta** [bshorta/date-generator-sketch#1]
When selecting a date format that includes an year, the range is limited from 1970 to 1972

**Comment by egofaylona** [comment]
Hi @bshorta, any update on this? I get this issue as well.

**Comment by bshorta** [comment]
Thanks for pointing that out, I'll work on a solution as soon as possible.

**Comment by egofaylona** [comment]
Awesome. Thanks!
  

  
  

  
  
>

**Comment by bshorta** [comment]
Fixed!
